# Page settings

baseURL = "https://eager-sinoussi-a55f5d.netlify.com/"
languageCode = "en"
title = "Simon Greenhalgh"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "Simon Greenhalgh"
    description = ""


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Simon Greenhalgh"
        tagline = "Marketing Major, Jazz Fan, "
        avatar = "Simon_Greenhalgh_cropped.png"







    [params.contact]
        enable = true
        location = "Salt Lake City, UT"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:859-757-5728"
        text = "859-757-5728"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:simongreenhalgh97@gmail.com"
        text = "simongreenhalgh97@gmail.com"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Microsoft Excel"
        [[params.skills.list.items]]
        details = "Customer Data Management"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Sales"
        [[params.skills.list.items]]
        details = "Management"
    





    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Bachelor of Business Administration"
        university = "University of Utah"
        dates = "expected 2020"
        [[params.education.list.items]]
        details = "Major: Marketing"
        [[params.education.list.items]]
        details = "Minor: Sports Management"
        


    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Spanish"
        level = "Professional"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Market Research Intern"
        dates = "August 2019 - present"
        company = "WINTERSTEIGER AG"
        details = ""
        [[params.experience.list.items]]
        details = "Researched and identified markets for new products using various analysis strategies."
        [[params.experience.list.items]]
        details = "Used data from research to write business plan that was used by upper level management."
        
       











    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/simon-greenhalgh-38038b178"
        title = "LinkedIn"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/SimonGhalgh"
        title = "Twitter"





